language: php

php:
  - 5.4

before_script:
  - sh -c "mysql -e 'CREATE DATABASE jslate;'"
  - chmod -R 777 ./app/tmp
  - sudo apt-get install lighttpd
  - phpenv rehash
  - set +H
  - echo "<?php
    class DATABASE_CONFIG {
        public \$default = array(
          'persistent' => false,
          'datasource' => 'Database/Mysql',
          'host' => '0.0.0.0',
          'login' => 'travis'
          'password' => '',
          'database' => 'jslate',
          'prefix' => ''
        );
    }" > app/Config/database.php

script:
  - sh -c "./lib/Cake/Console/cake test core AllTests --stderr"

notifications:
  email: false
